export { AdminPageContainer } from './Admin/AdminPageContainer/AdminPageContainer';
export { DishDescription } from './DishDescription/DishDescription';
export { Slider } from './Slider/Slider';
export { TableCard } from './TableCard/TableCard';
export { Statisctics } from './Statistics/Statisctics';
export { Sidebar } from './Sidebar/Sidebar';
export { OrdersButton } from './OrdersButton/OrdersButton';
export { Orders } from './Orders/Orders';
export { Cart } from './Cart/Cart';
export { ConfirmModal } from './ConfirmModal/ConfirmModal';
export { DishesItem, StatusCardItem, DishesList } from './Cook';
export { Dialog } from './Dialog/Dialog';
export { CheckboxTables } from './CheckboxTables/CheckboxTables';
